export const laporanConstants = {
    EXPORT_ORDER_REQUEST: 'USERS_EXPORT_ORDER_REQUEST',
    EXPORT_ORDER_SUCCESS: 'USERS_EXPORT_ORDER_SUCCESS',
    EXPORT_ORDER_FAILURE: 'USERS_EXPORT_ORDER_FAILURE',    


    EXPORT_USER_REQUEST: 'USERS_EXPORT_USER_REQUEST',
    EXPORT_USER_SUCCESS: 'USERS_EXPORT_USER_SUCCESS',
    EXPORT_USER_FAILURE: 'USERS_EXPORT_USER_FAILURE',    
};
